---
- name: Checking scripts already installed or not
  stat:
    path: "{{ bigdata_dir_scripts }}"
  register: scripts_installed_status

- name: Creating Script and log directory
  file:
    path: "{{ item }}"
    state: directory
  register: dir_creation_status
  with_items:
     - "{{ bigdata_dir }}/pids"
     - "{{ bigdata_dir }}/logs"
     - "{{ bigdata_dir_scripts }}"

- name: Copy bigadm.sh 
  template: src=bigadm.sh dest="{{ bigdata_dir_scripts }}/bigadm.sh" mode=644

- name: Copy bigdata-user-profile.sh 
  template: src=bigdata-user-profile.sh dest="{{ bigdata_dir_scripts }}/bigdata-user-profile.sh" mode=644

- name: "Creating Scripts Env soft link"
  file:
   src: "{{ bigdata_dir_scripts }}"
   dest: "{{ bigdata_env_dir }}/scripts"
   state: link
#  when: not hadoop_installed_status.stat.exists

