- name: Checking zookeeper already installed or not
  become: true
  become_user: "{{ HADOOP_USER }}"
  stat:
    path: "{{ bigdata_new_release_dir }}/apache-zookeeper-{{ zookeeper_version }}-bin"
  register: zookeeper_installed_status

- name: Display all variables/facts known for a host
  become: true
  become_user: "{{ HADOOP_USER }}"
  debug:
    msg: "{% if zookeeper_installed_status.stat.exists %} Zookeeper is already installed {% else %} Zookeeper not installed {% endif %}"

- name: Check zookeeper archive file exist
  become: true
  become_user: "{{ HADOOP_USER }}"
  stat:
    path: "{{ tmp_dir }}/{{ zookeeper_file }}"
  register: zookeeper_download_file
  when: not zookeeper_installed_status.stat.exists

- name: Creates directory
  become: true
  become_user: "{{ HADOOP_USER }}"
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ HADOOP_USER }}"
    group: "{{ HADOOP_USER }}"
  register: dir_creation_status
  when: not zookeeper_installed_status.stat.exists
  with_items:
     - "{{ tmp_dir }}"
     - "{{ tmp_dir_cache }}"
     - "{{ bigdata_dir }}"
     - "{{ bigdata_env_dir }}"
     - "{{ bigdata_new_release_dir }}"

- name: Transfer Zookeeper binaries
  become: true
  become_user: "{{ HADOOP_USER }}"
  copy: src={{ tmp_dir }}/{{ zookeeper_file }} dest={{ tmp_dir_cache }}/{{ zookeeper_file }}
  when: not zookeeper_installed_status.stat.exists


- name: "Moving Files workspace"
  become: true
  become_user: "{{ HADOOP_USER }}"
  command: mv {{ tmp_dir_cache }}/{{ zookeeper_file }} {{ tmp_dir }}/{{ zookeeper_file }}
  when: not zookeeper_installed_status.stat.exists

- name: Unzip Zookeeper
  become: true
  become_user: "{{ HADOOP_USER }}"
  shell: "tar zxf {{ tmp_dir }}/{{ zookeeper_file }} -C {{ bigdata_new_release_dir }}"
  when: not zookeeper_installed_status.stat.exists

- name: "Creating zookeeper Env soft link"
  become: true
  become_user: "{{ HADOOP_USER }}"
  file:
   src: "{{ bigdata_new_release_dir }}/apache-zookeeper-{{ zookeeper_version }}-bin" 
   dest: "{{ bigdata_env_dir }}/zookeeper"
   state: link
#  when: not zookeeper_installed_status.stat.exists

- name: Setting-up Executable permissions to bin/sbin folders
  become: true
  become_user: "{{ HADOOP_USER }}"
  file:
    path: "{{ item }}"
    state: directory
    mode: 0775
    recurse: yes
  register: dir_creation_status
  with_items:
     - "{{ bigdata_env_dir }}/zookeeper/bin"

