---
- name: Copy Hadoop core-site.xml
  template: src=core-site.xml dest="{{ bigdata_new_release_dir }}/hadoop-{{ hadoop_version }}/etc/hadoop/" mode=644

- name: Copy Hadoop hdfs-site.xml
  template: src=hdfs-site.xml dest="{{ bigdata_new_release_dir }}/hadoop-{{ hadoop_version }}/etc/hadoop/" mode=644

- name: Copy Hadoop mapred-site.xml
  template: src=mapred-site.xml dest="{{ bigdata_new_release_dir }}/hadoop-{{ hadoop_version }}/etc/hadoop/" mode=644

- name: Copy Hadoop hadoop-env.sh 
  template: src=hadoop-env.sh dest="{{ bigdata_new_release_dir }}/hadoop-{{ hadoop_version }}/etc/hadoop/" mode=644
