- name: Downloading Binaris
  hosts: buildserver
  #user: hadoop
  vars_files:
    - vars/bigdata_build_versions.yml 
    - vars/main.yml 
    - vars/bigdata_install_property.yml 
    - vars/bigdata_site_xml_properties.yml
  vars:
    download_hadoop: true
    download_hive: true
    download_tez: true
    download_kafka: true
    download_spark: true
    download_derby: true
    download_impala: true
    download_zookeeper: true
#  become: true
  
  roles:
    - role: downloads 
