- name: Downloading Binaris
  hosts: nameNode:dataNode 
  any_errors_fatal: true
  vars_files:
    - vars/bigdata_build_versions.yml 
    - vars/main.yml 
    - vars/bigdata_install_property.yml 
    - vars/bigdata_site_xml_properties.yml 
  vars:
    install_hadoop: true 
    config_hadoop: true 
    is_hadoop_already_installed: false
#  become: true
  
  roles:
    - role: hadoop_ha
