- name: Downloading Binaris
  hosts: zookeeperNode 
  any_errors_fatal: true
  vars_files:
    - vars/bigdata_build_versions.yml 
    - vars/main.yml 
    - vars/bigdata_install_property.yml 
    - vars/bigdata_site_xml_properties.yml 
  vars:
    install_zookeeper: true 
    config_zookeeper: true
  
  roles:
    - role: zookeeper 
