- name: Downloading Binaris
  hosts: nameNode:dataNode:hiveNode 
  any_errors_fatal: true
  vars_files:
    - vars/bigdata_build_versions.yml 
    - vars/main.yml 
    - vars/bigdata_install_property.yml 
    - vars/bigdata_site_xml_properties.yml 
  vars:
    user_name: "{{ lookup('env','HOME') }}"
    install_scripts: true
  
  roles:
    - role: scripts 
