- name: Downloading Binaris
  hosts: sparkMaster:sparkWorker
  any_errors_fatal: true
  vars_files:
    - vars/bigdata_build_versions.yml 
    - vars/main.yml 
    - vars/bigdata_install_property.yml 
    - vars/bigdata_site_xml_properties.yml 
  vars:
    install_hadoop: true 
    config_hadoop: true
    install_spark: true 
    config_spark: true
#  become: true
  
  roles:
    - role: hadoop 
    - role: spark
