- name: Downloading Binaris
  hosts: hiveNode 
  user: hadoop 
  any_errors_fatal: true
  vars_files:
    - vars/bigdata_build_versions.yml 
    - vars/main.yml 
    - vars/bigdata_install_property.yml 
    - vars/bigdata_site_xml_properties.yml 
  vars:
    install_scripts: true
  
  roles:
    - role: scripts 
