- name: Checking Spark arcspark file exsit
  stat:
    path: "{{ tmp_dir }}/{{ spark_file }}"
  register: spark_download_file


- name: Creates directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
     - "{{ tmp_dir }}"
     - "{{ tmp_dir_cache }}"


- name: Download Spark
  get_url:
    url: "{{ spark_url }}"
    dest: "{{ tmp_dir_cache }}/{{ spark_file }}"
    validate_certs : no
  when: not spark_download_file.stat.exists

- name: "Moving Files"
  command: mv {{ tmp_dir_cache }}/{{ spark_file }} {{ tmp_dir }}/{{ spark_file }}
  when: not spark_download_file.stat.exists 
