- name: Checking Impala archive file exsit
  stat:
    path: "{{ tmp_dir }}/{{ impala_file }}"
  register: impala_download_file


- name: Creates directory
  become: true
  become_user: hadoop
  file:
    path: "{{ item }}"
    state: directory
  with_items:
     - "{{ tmp_dir }}"
     - "{{ tmp_dir_cache }}"


- name: Download Impala
  become: true
  become_user: hadoop
  get_url:
    url: "{{ impala_url }}"
    dest: "{{ tmp_dir_cache }}/{{ impala_file }}"
    owner: "{{ HADOOP_USER }}"
    group: "{{ HADOOP_USER }}"
  when: not impala_download_file.stat.exists

- name: "Moving Files"
  become: true
  become_user: hadoop
  command: mv {{ tmp_dir_cache }}/{{ impala_file }} {{ tmp_dir }}/{{ impala_file }}
  when: not impala_download_file.stat.exists 
