- name: Check hadoop archive file exist
  stat:
    path: "{{ tmp_dir }}/{{ hadoop_file }}"
  register: hadoop_download_file

- name: Checking Hive archive file exsit
  stat:
    path: "{{ tmp_dir }}/{{ hive_file }}"
  register: hive_download_file


- name: Creates directory
  become: true
  become_user: hadoop
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ HADOOP_USER }}"
    group: "{{ HADOOP_USER }}"
  with_items:
     - "{{ tmp_dir }}"
     - "{{ tmp_dir_cache }}"


- name: Download Hadoop
  become: true
  become_user: hadoop
  get_url:
    url: "{{ hadoop_url }}"
    dest: "{{ tmp_dir_cache }}/{{ hadoop_file }}"
  when: not hadoop_download_file.stat.exists

- name: "Moving Files"
  become: true
  become_user: hadoop
  command: mv {{ tmp_dir_cache }}/{{ hadoop_file }} {{ tmp_dir }}/{{ hadoop_file }}
  when: not hadoop_download_file.stat.exists 
