- name: Checking Impala archive file exsit
  stat:
    path: "{{ tmp_dir }}/{{ impala_file }}"
  register: impala_download_file


- name: Creates directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
     - "{{ tmp_dir }}"
     - "{{ tmp_dir_cache }}"


- name: Download Impala
  get_url:
    url: "{{ impala_url }}"
    dest: "{{ tmp_dir_cache }}/{{ impala_file }}"
  when: not impala_download_file.stat.exists

- name: "Moving Files"
  command: mv {{ tmp_dir_cache }}/{{ impala_file }} {{ tmp_dir }}/{{ impala_file }}
  when: not impala_download_file.stat.exists 
