- name: Checking Hive archive file exsit
  stat:
    path: "{{ tmp_dir }}/{{ hive_file }}"
  register: hive_download_file


- name: Creates directory
  become: true
  become_user: hadoop
  file:
    path: "{{ item }}"
    state: directory
  with_items:
     - "{{ tmp_dir }}"
     - "{{ tmp_dir_cache }}"


- name: Download Hive
  become: true
  become_user: hadoop
  get_url:
    url: "{{ hive_url }}"
    dest: "{{ tmp_dir_cache }}/{{ hive_file }}"
    owner: "{{ HADOOP_USER }}"
    group: "{{ HADOOP_USER }}"
  when: not hive_download_file.stat.exists

- name: "Moving Files"
  become: true
  become_user: hadoop
  command: mv {{ tmp_dir_cache }}/{{ hive_file }} {{ tmp_dir }}/{{ hive_file }}
  when: not hive_download_file.stat.exists 
