- name: Checking Kafka archive file exsit
  stat:
    path: "{{ tmp_dir }}/{{ kafka_file }}"
  register: kafka_download_file


- name: Creates directory
  become: true
  become_user: hadoop
  file:
    path: "{{ item }}"
    state: directory
  with_items:
     - "{{ tmp_dir }}"
     - "{{ tmp_dir_cache }}"


- name: Download Kafka
  become: true
  become_user: hadoop
  get_url:
    url: "{{ kafka_url }}"
    dest: "{{ tmp_dir_cache }}/{{ kafka_file }}"
    owner: "{{ HADOOP_USER }}"
    group: "{{ HADOOP_USER }}"
    validate_certs: no
  when: not kafka_download_file.stat.exists

- name: "Moving Files"
  become: true
  become_user: hadoop
  command: mv {{ tmp_dir_cache }}/{{ kafka_file }} {{ tmp_dir }}/{{ kafka_file }}
  when: not kafka_download_file.stat.exists 
