---
- include_tasks: download_hadoop.yml
  when: download_hadoop
- include_tasks: download_hive.yml
  when: download_hive
- include_tasks: download_tez.yml
  when: download_tez
- include_tasks: download_spark.yml
  when: download_spark
- include_tasks: download_derby.yml
  when: download_derby
- include_tasks: download_kafka.yml
  when: download_kafka
- include_tasks: download_impala.yml
  when: download_impala
- include_tasks: download_zookeeper.yml
  when: download_zookeeper
