        <property>
                <name>fs.defaultFS</name>
                <value>hdfs://{{ NAMNODE_HA }}</value>
        </property>
    {% for host in groups['journalNode'] %}
         <property>
                <name>dfs.namenode.rpc-address.{{ NAMNODE_HA }}.{{ host.split(".")[0] }}</name>
                <value>{{ host }}:8020</value>
         </property>
    {% endfor %}

    {% for host in groups['journalNode'] %}
        <property>
                <name>dfs.namenode.http-address.{{ NAMNODE_HA }}.{{ host.split(".")[0] }}</name>
                <value>{{ host }}:9870</value>
        </property>
    {% endfor %}

