---
- name: enable_zookeeper_service
  become: true
  become_user: root
  command: systemctl enable zookeeper.service
  when: inventory_hostname in groups['zookeeperNode']

- name: starting_zookeeper
  become: yes
  become_user: "{{ HADOOP_USER }}"
  shell: source /usr/bigdata/Envs/scripts/bigdata-user-profile.sh;/usr/bigdata/Miniconda3/bin/python3 /usr/bigdata/Envs/scripts/bigadm.py --start zookeeper --type service
  when:
    - inventory_hostname in groups["zookeeperNode"]
    
