- name: Checking Tez archive file exsit
  stat:
    path: "{{ tmp_dir }}/{{ cloudera_hue_file }}"
  register: hue_download_file


- name: Creates directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
     - "{{ tmp_dir }}"
     - "{{ tmp_dir_cache }}"


- name: Download Hadoop
  get_url:
    url: "{{ cloudera_hue_url }}"
    dest: "{{ tmp_dir_cache }}/{{ cloudera_hue_file }}"
  when: not hue_download_file.stat.exists

- name: "Moving Files"
  command: mv {{ tmp_dir_cache }}/{{ cloudera_hue_file }} {{ tmp_dir }}/{{ cloudera_hue_file }}
  when: not hue_download_file.stat.exists 
